# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-25 15:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('del_date', models.DateTimeField(null=True)),
                ('spam_flag', models.BooleanField(default=False)),
                ('read_flag', models.BooleanField(default=False)),
                ('read_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoxModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='asks',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask.BoxModel'),
        ),
    ]
